[build]
builder = "nixpacks"
buildCommand = "npm run generate-prisma && npx nx run communication:build:production"

[deploy]
startCommand = "node dist/apps/communication/main.js"
restartPolicyType = "ON_FAILURE"
